import type { Metadata } from 'next'
import { Geist, Geist_Mono, Poppins } from 'next/font/google'
import './globals.css'

import { ConfigProvider } from '@/contexts/ConfigContext'
import { AuthProvider   } from '@/contexts/AuthContext'

const geistSans = Geist({  variable: '--font-geist-sans',  subsets: ['latin'] })
const geistMono = Geist_Mono({ variable: '--font-geist-mono', subsets: ['latin'] })
const poppins   = Poppins({ variable: '--font-poppins', subsets: ['latin'], weight: '400' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-BR">
      <body className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} antialiased`}>
        {/* Se tornou opcional → não precisa passar config */}
        <ConfigProvider config={null}>   
          <AuthProvider>
            {children}
          </AuthProvider>
        </ConfigProvider>
      </body>
    </html>
  )
}
